CREATE TABLE gallery(
    gal_no NUMBER(6)
        CONSTRAINT GAL_NO_PK PRIMARY KEY,
    gal_writer VARCHAR2(10 CHAR)
        CONSTRAINT GAL_ID_FK REFERENCES member(id)
        CONSTRAINT GAL_ID_NN NOT NULL,
    gal_body VARCHAR2(4000)
        CONSTRAINT GAL_BODY_NN NOT NULL,
    gal_wdate DATE DEFAULT sysdate
        CONSTRAINT GAL_DATE_NN NOT NULL,
    gal_count NUMBER DEFAULT 0
        CONSTRAINT GAL_CNT_NN NOT NULL,
    gal_upno NUMBER(6),
    gal_isshow CHAR(1) DEFAULT 'Y'
        CONSTRAINT GAL_SHOW_CK CHECK(gal_isshow IN ('Y', 'N'))
        CONSTRAINT GAL_SHOW_NN NOT NULL
);

CREATE TABLE photo(
    pno NUMBER(6)
        CONSTRAINT PHOTO_NO_PK PRIMARY KEY,
    galno NUMBER(6)
        CONSTRAINT PHOTO_GALNO_FK REFERENCES gallery(gal_no)
        CONSTRAINT PHOTO_GALNO_NN NOT NULL,
    photo_oname VARCHAR2(300 CHAR)
        CONSTRAINT PHOTO_ONAME_NN NOT NULL,
    photo_sname VARCHAR2(300 CHAR)
        CONSTRAINT PHOTO_SNAME_UK UNIQUE
        CONSTRAINT PHOTO_SNAME_NN NOT NULL,
    photo_dir VARCHAR2(300 CHAR) DEFAULT '/photo/'
        CONSTRAINT PHOTO_DIR_NN NOT NULL,
    p_date DATE DEFAULT sysdate
        CONSTRAINT PHOTO_DATE_NN NOT NULL,
    p_isshow CHAR(1) DEFAULT 'Y'
        CONSTRAINT PHOTO_SHOW_CK CHECK(p_isshow IN('Y', 'N'))
        CONSTRAINT PHOTO_SHOW_NN NOT NULL
);






